---
- name: Retrieve and store running configuration from multiple switches via jump host
  hosts: 172.19.98.20  # Jump host
  gather_facts: yes   # Needed for ansible_date_time

  vars:
    target_switch_username: "{{ target_switch_username }}"
    target_switch_password: "{{ target_switch_password }}"
    base_dir: "/tmp/configurations"  # Base directory for saving config files

  tasks:
    - name: Ensure base directory exists
      file:
        path: "{{ base_dir }}"
        state: directory
        mode: '0755'

    - name: Set current date variable (DD-MM-YYYY)
      set_fact:
        current_date: "{{ ansible_date_time.date | regex_replace('(\\d{4})-(\\d{2})-(\\d{2})', '\\3-\\2-\\1') }}"

    - name: Ensure today's date directory exists
      file:
        path: "{{ base_dir }}/{{ current_date }}"
        state: directory
        mode: '0755'

    - name: Retrieve configuration from switches in group switch_cisco
      include_tasks: get_config_from_switch.yml
      loop: "{{ groups['switch_cisco'] }}"
      loop_control:
        loop_var: target_switch
