---
- name: Retrieve and output Cisco running configuration for copy-paste
  hosts: 172.19.98.20  # IP of the Jump Host
  gather_facts: no

  vars:
    target_host: 172.16.3.3  # IP of the Target Switch
    target_switch_username: "{{ target_switch_username }}"  # Username for the switch
    target_switch_password: "{{ target_switch_password }}"  # Password for the switch

  tasks:
    - name: Telnet to the target switch, disable pagination, get running config, and exit
      expect:
        command: "telnet {{ target_host }}"
        responses:
          "Username:": "{{ target_switch_username }}"
          "Password:": "{{ target_switch_password }}"
          "SWOCESC0-1#": "terminal length 0\nshow running-config\nexit\n"
        timeout: 120
        echo: yes
      register: running_config_result
      failed_when: false

    - name: Extract configuration portion from output
      set_fact:
        # Splits the output on "Current configuration :" and then on "SWOCESC0-1#exit" to isolate only the config.
        config_text: "{{ running_config_result.stdout.split('Current configuration :')[1].split('SWOCESC0-1#exit')[0] }}"

    - name: Display configuration for copy-paste
      debug:
        msg: "{{ config_text | regex_replace('\\r', '') }}"
