---
- name: Test Telnet Connection from Jump Host to Target Switch
  hosts: 172.19.98.20
  gather_facts: no

  vars:
    target_host: 172.16.3.3         # Target switch IP
    target_switch_username: "{{ target_switch_username }}"  # e.g., OAdmin
    target_switch_password: "{{ target_switch_password }}"  # e.g., xxx123

  tasks:
    - name: Telnet from jump host to target switch and exit on prompt
      expect:
        command: "telnet {{ target_host }}"
        responses:
          "Username:": "{{ target_switch_username }}"
          "Password:": "{{ target_switch_password }}"
          # When the switch prompt is seen, send "exit" to close the session.
          "SWOCESC0-1#": "exit\n"
        timeout: 60
        echo: yes
      register: telnet_result

    - name: Display telnet session output
      debug:
        var: telnet_result.stdout
