---
- name: Get running configuration from target switch via Telnet through Jump Host
  hosts: 172.19.98.20
  gather_facts: no

  vars:
    target_host: 172.16.3.3
    target_switch_username: "{{ target_switch_username }}"
    target_switch_password: "{{ target_switch_password }}"
    target_switch_command: "show running-config"

  tasks:
    - name: Telnet to the target switch and send terminal length 0 to disable pagination
      expect:
        command: "telnet {{ target_host }}"
        responses:
          "Username:": "{{ target_switch_username }}"
          "Password:": "{{ target_switch_password }}"
          "SWOCESC0-1#": "terminal length 0\n"  # Disable pagination
        timeout: 60  # Adjust timeout for the command
        echo: yes
      register: telnet_result

    - name: Run the show running-config command after disabling pagination
      expect:
        command: "telnet {{ target_host }}"
        responses:
          "Username:": "{{ target_switch_username }}"
          "Password:": "{{ target_switch_password }}"
          "SWOCESC0-1#": "{{ target_switch_command }}\n"  # Run the show running-config command
        timeout: 60  # Shorter timeout for this step
        echo: yes
      register: show_running_config

    - name: Display the full output of the show running-config command
      debug:
        var: show_running_config.stdout

    - name: Display any errors from the Telnet session (stderr)
      debug:
        var: show_running_config.stderr
