---
# cisco_backup_ssh_proxy.yml
- name: Backup Cisco Config via SSH Proxy
  hosts: 172.16.3.3  # Directly target Cisco device
  gather_facts: no
  connection: ansible.netcommon.network_cli

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: "{{ target_switch_username }}"
    ansible_password: "{{ target_switch_password }}"
    ansible_ssh_common_args: >-
      -o ProxyCommand="ssh -W %h:%p -q jump_user@172.19.98.20"

  tasks:
    - name: Backup running configuration
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: "/backups/cisco/"
      register: backup_result

    - name: Show backup path
      debug:
        msg: "Backup created at {{ backup_result.backup_path }}"
