---
- name: Verify current working directory in AWX/WSL
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Check current directory
      shell: pwd
      register: current_directory

    - name: Show current working directory
      debug:
        var: current_directory.stdout
