---
- name: Connect to target switch via telnet and run show running-configuration
  hosts: localhost  # Running from localhost as we are working with jump host and target switch
  gather_facts: no

  vars:
    jump_host: 172.19.98.20  # Jump host IP (for SSH tunneling)
    target_host: 172.16.3.3  # Target switch IP

  tasks:
    - name: Set up the jump host SSH connection
      ansible.builtin.set_fact:
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -p 222 {{ jump_host }}"'

    - name: Use target_switch_pass credentials for Telnet connection to target switch
      expect:
        command: "telnet {{ target_host }}"
        responses:
          "Username:": "{{ ansible_user }}"  # Use the username from the AWX credential (e.g., target_switch_user)
          "Password:": "{{ ansible_password }}"  # Use the password from the AWX credential (e.g., target_switch_pass)
        timeout: 30
        register: telnet_output

    - name: Send 'show running-configuration' command after login
      expect:
        command: "show running-configuration"
        responses:
          "Password:": "{{ ansible_password }}"  # Reuse password if prompted again
        timeout: 30
        register: running_config_output

    - name: Save running configuration to a file
      copy:
        content: "{{ running_config_output.stdout }}"
        dest: "/tmp/running_config_{{ target_host }}.txt"

    - name: Display the show running-configuration output
      debug:
        var: running_config_output.stdout
