---
- name: Get running configuration from target switch via Telnet through Jump Host
  hosts: 172.19.98.20
  gather_facts: no

  vars:
    target_host: 172.16.3.3
    target_switch_username: "{{ target_switch_username }}"
    target_switch_password: "{{ target_switch_password }}"
    target_switch_command: "{{ target_switch_command }}"  # Command to run, provided by AWX extra vars

  tasks:
    - name: Telnet to the target switch
      expect:
        command: "telnet {{ target_host }}"
        responses:
          "Username:": "{{ target_switch_username }}"
          "Password:": "{{ target_switch_password }}"
          "SWOCESC0-1#": "{{ target_switch_command }}\n"  # Command to run (e.g., 'show running-configuration')
        timeout: 60  # Timeout of 60 seconds
        echo: yes
      register: initial_telnet_result

    - name: Handle pagination and keep reading until no more --More-- prompt
      expect:
        command: "telnet {{ target_host }}"
        responses:
          "Username:": "{{ target_switch_username }}"
          "Password:": "{{ target_switch_password }}"
          "SWOCESC0-1#": "{{ target_switch_command }}\n"  # Command to run (e.g., 'show running-configuration')
          "SWOCESC0-1#": "\n"  # Send spacebar to handle --More-- prompt
        timeout: 60  # Timeout of 60 seconds
        echo: yes
      register: paginated_telnet_result
      until: paginated_telnet_result.stdout is search("SWOCESC0-1#")
      retries: 10  # Retry 10 times (adjust as needed)
      delay: 5  # Delay between retries (adjust if needed)

    - name: Display the raw telnet session output (stdout)
      debug:
        var: paginated_telnet_result.stdout

    - name: Display any errors from the Telnet session (stderr)
      debug:
        var: paginated_telnet_result.stderr

    - name: Display the status code of the Telnet session
      debug:
        var: paginated_telnet_result.rc
