---
- name: Test SSH and Show Version
  hosts: 172.19.98.20
  gather_facts: no

  tasks:
    - name: Test SSH Connection
      ansible.builtin.ping:

    - name: Run Show Version Command
      ansible.builtin.command: show version
      register: version_output

    - name: Display Show Version Output
      debug:
        var: version_output.stdout
