---
- name: Test Telnet to Target Switch via Jump Host and run show running-configuration
  hosts: localhost
  gather_facts: no

  vars:
    jump_host: 172.19.98.20  # Jump host IP (SSH connection)
    target_host: 172.16.3.3  # Target switch IP (Telnet connection)
    target_switch_pass: "{{ target_switch_password }}"  # Password for the target switch
    jump_host_ssh_port: 222  # SSH port for jump host, if not default 22

  tasks:
    - name: Set up the jump host SSH connection to keep the session open
      ansible.builtin.set_fact:
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -p {{ jump_host_ssh_port }} {{ jump_host }}"'

    - name: Use the jump host to connect via Telnet to the target switch
      expect:
        command: "telnet {{ target_host }}"
        responses:
          "Username:": "{{ ansible_user }}"  # Use the jump host username
          "Password:": "{{ ansible_password }}"  # Use the jump host password
        timeout: 30
        echo: yes
      delegate_to: localhost

    - name: Send 'show running-configuration' command to the target switch
      expect:
        command: "show running-configuration"
        responses:
          "Password:": "{{ target_switch_pass }}"  # Target switch password for Telnet login
        timeout: 30
        echo: yes
      delegate_to: localhost

    - name: Display the show running-configuration output
      debug:
        var: running_config_output.stdout
      delegate_to: localhost
