---
- name: Check Ping of IP 172.19.98.20
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Ping the IP 172.19.98.20
      ansible.builtin.ping:
      delegate_to: 172.19.98.20
      vars:
        ansible_port: 222  # Change this to your actual SSH port
