---
- name: Check the current user inside AWX
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check the current user inside AWX
      command: whoami
      register: awx_user

    - name: Display AWX user
      debug:
        var: awx_user.stdout
