---
- name: Test SSH and Show Version
  hosts: 172.19.98.20
  gather_facts: no

  tasks:
    - name: Test SSH Connection
      ansible.builtin.ping:

    - name: Run uname -a Command
      ansible.builtin.command: uname -a
      register: version_output

    - name: Display uname -a Output
      debug:
        var: version_output.stdout
