---
- name: Get running configuration from target switch via Telnet through Jump Host
  hosts: 172.19.98.20
  gather_facts: no

  vars:
    target_host: 172.16.3.3
    target_switch_username: "{{ target_switch_username }}"
    target_switch_password: "{{ target_switch_password }}"
    target_switch_command: "show running-config"

  tasks:
    - name: Telnet to the target switch and retrieve the configuration
      expect:
        command: "telnet {{ target_host }}"
        responses:
          "Username:": "{{ target_switch_username }}"
          "Password:": "{{ target_switch_password }}"
          "SWOCESC0-1#": "{{ target_switch_command }}\n"
        timeout: 120  # Increased timeout to handle large outputs
        echo: yes
      register: telnet_result

    - name: Handle pagination (send space for --More-- prompt)
      expect:
        command: "telnet {{ target_host }}"
        responses:
          "Username:": "{{ target_switch_username }}"
          "Password:": "{{ target_switch_password }}"
          "SWOCESC0-1#": "{{ target_switch_command }}\n"  # Repeat the command if needed
          "--More--": " "  # Send space to handle pagination after every --More-- prompt
        timeout: 300  # Increased timeout to handle long outputs
        echo: yes
      register: telnet_result_full
      until: "'SWOCESC0-1#' in telnet_result_full.stdout"  # Keep going until the final prompt appears
      retries: 20  # Retry 20 times if necessary (for long outputs)
      delay: 10  # 10-second delay between retries

    - name: Display the full output of the Telnet session
      debug:
        var: telnet_result_full.stdout

    - name: Display any errors from the Telnet session (stderr)
      debug:
        var: telnet_result_full.stderr

    - name: Display the status code of the Telnet session
      debug:
        var: telnet_result_full.rc
